/** Traductions anglaises — domaine « ssh ». Clé = chaîne française exacte. */
export const ssh: Record<string, string> = {
  // RemoteExplorer.tsx
  'SFTP : {error}': 'SFTP: {error}',
  'Édition : {error}': 'Edit: {error}',
  '{name} ouvert — chaque sauvegarde est ré-téléversée sur le serveur.':
    '{name} opened — every save is re-uploaded to the server.',
  'Téléchargement : {ok} OK, {count} échec(s) — {err}':
    'Download: {ok} OK, {count} failure(s) — {err}',
  '{n} élément téléchargé.': '{n} item downloaded.',
  '{n} éléments téléchargés.': '{n} items downloaded.',
  'Téléversement : {ok} OK, {count} échec(s) — {err}':
    'Upload: {ok} OK, {count} failure(s) — {err}',
  '{n} élément téléversé vers {path}': '{n} item uploaded to {path}',
  '{n} éléments téléversés vers {path}': '{n} items uploaded to {path}',
  'Redéploiement : {ok} OK, {count} échec(s) — {err}':
    'Redeploy: {ok} OK, {count} failure(s) — {err}',
  'Redéployé : {n} élément → {dir}': 'Redeployed: {n} item → {dir}',
  'Redéployé : {n} éléments → {dir}': 'Redeployed: {n} items → {dir}',
  'Nouveau dossier : {error}': 'New folder: {error}',
  'Renommage : {error}': 'Rename: {error}',
  "Supprimer {n} élément du SERVEUR ? Pas de corbeille en SFTP : c'est définitif.":
    'Delete {n} item from the SERVER? No trash in SFTP: this is permanent.',
  "Supprimer {n} éléments du SERVEUR ? Pas de corbeille en SFTP : c'est définitif.":
    'Delete {n} items from the SERVER? No trash in SFTP: this is permanent.',
  'Suppression : {ok} OK, {count} échec(s) — {err}':
    'Delete: {ok} OK, {count} failure(s) — {err}',
  'Mot de passe enregistré oublié.': 'Saved password forgotten.',
  'Oublier le mot de passe enregistré pour ce serveur':
    'Forget the saved password for this server',
  'Ouvrir un terminal SSH dans {path}': 'Open an SSH terminal in {path}',
  'Se déconnecter et fermer': 'Disconnect and close',
  'Connexion à {host}…': 'Connecting to {host}…',
  'Première connexion à ce serveur.': 'First connection to this server.',
  'Empreinte :': 'Fingerprint:',
  'Mémorisée après validation ; toute future différence bloquera la connexion.':
    'Remembered after approval; any future mismatch will block the connection.',
  'Faire confiance': 'Trust',
  Annuler: 'Cancel',
  'Mot de passe —': 'Password —',
  'Retenir le mot de passe (chiffré par Windows)': 'Remember the password (encrypted by Windows)',
  'Utilisé pour cette session, jamais stocké.': 'Used for this session only, never stored.',
  'Se connecter': 'Connect',
  "Le serveur n'a pas répondu — beaucoup limitent les connexions rapprochées (anti-abus). Patientez ~30 secondes avant de réessayer.":
    'The server did not respond — many limit rapid reconnection attempts (anti-abuse). Wait about 30 seconds before retrying.',
  Réessayer: 'Retry',
  'Dossier parent': 'Parent folder',
  Actualiser: 'Refresh',
  '{path}\nCliquer : dossiers récents sur ce serveur': '{path}\nClick: recent folders on this server',
  'Nouveau dossier distant': 'New remote folder',
  Renommer: 'Rename',
  'Supprimer du serveur (définitif)': 'Delete from server (permanent)',
  'Télécharger la sélection distante vers {dir}': 'Download the remote selection to {dir}',
  'le volet local': 'the local pane',
  Télécharger: 'Download',
  'Téléverser la sélection du volet local ici (ou glissez-déposez)':
    'Upload the local pane selection here (or drag and drop)',
  Téléverser: 'Upload',
  'Envoyer le CONTENU de {name}/ dans {path} (sans créer le dossier — le geste « déployer dist »)':
    'Send the CONTENTS of {name}/ into {path} (without creating the folder — the "deploy dist" move)',
  'Contenu de {name}/ →': 'Contents of {name}/ →',
  'Rejouer le dernier envoi : {label}': 'Replay the last upload: {label}',
  Redéployer: 'Redeploy',
  'Chargement…': 'Loading…',
  'Dossier vide — glissez des fichiers du volet local pour les téléverser.':
    'Empty folder — drag files from the local pane to upload them.',
  'Nom du nouveau dossier…': 'New folder name…',
  '{path}\nDouble-clic : modifier (ré-téléversé à la sauvegarde)':
    '{path}\nDouble-click: edit (re-uploaded on save)',
  'Modifier (ré-téléversé à chaque sauvegarde)': 'Edit (re-uploaded on every save)',
  'Glissez du volet local vers ici pour téléverser · téléchargements → dossier local actif':
    'Drag from the local pane here to upload · downloads → active local folder',

  // lib/ssh.ts (describeForward, toSshConfigText)
  'serveur:{port} → {host}:{destPort} (distant)': 'server:{port} → {host}:{destPort} (remote)',
  'Généré par GVue — collez dans ~/.ssh/config (ou incluez ce fichier).':
    'Generated by GVue — paste into ~/.ssh/config (or include this file).',
  '{name} : déjà défini dans votre ~/.ssh/config (alias).':
    '{name}: already defined in your ~/.ssh/config (alias).',

  // ServerAddForm.tsx
  'Modifier « {name} »': 'Edit "{name}"',
  'Ajouter un serveur': 'Add a server',
  'Fermer (Échap)': 'Close (Esc)',
  'Serveur (hôte ou IP)': 'Server (host or IP)',
  'Ex. : serveur.exemple.com ou 192.168.1.10 — « user@hôte » est accepté aussi.':
    'E.g.: server.example.com or 192.168.1.10 — "user@host" is accepted too.',
  'serveur.exemple.com': 'server.example.com',
  Utilisateur: 'User',
  'Compte de connexion (root, ubuntu, deploy…).': 'Login account (root, ubuntu, deploy…).',
  Port: 'Port',
  '22 par défaut.': '22 by default.',
  Libellé: 'Label',
  "Nom affiché dans la liste. Vide = le nom d'hôte.": 'Name shown in the list. Empty = the hostname.',
  'Prod — site vitrine': 'Prod — showcase site',
  'Mot de passe (facultatif)': 'Password (optional)',
  "Laissez vide pour conserver l'existant. S'il est saisi, il est chiffré par Windows.":
    'Leave empty to keep the existing one. If entered, it is encrypted by Windows.',
  "Laissez vide pour qu'il soit demandé à la connexion. S'il est saisi, il est chiffré par Windows — les clés SSH restent plus sûres.":
    'Leave empty to be asked for it at connection time. If entered, it is encrypted by Windows — SSH keys remain safer.',
  'Chiffrement indisponible sur cette machine : le mot de passe sera demandé à chaque connexion.':
    'Encryption unavailable on this machine: the password will be requested at every connection.',
  indisponible: 'unavailable',
  'Tunnels (redirections de port)': 'Tunnels (port forwarding)',
  'Une par ligne. « 3001:localhost:3001 » rend le service distant accessible sur http://localhost:3001. Préfixez par R (distant) ou D (proxy SOCKS).':
    'One per line. "3001:localhost:3001" makes the remote service available at http://localhost:3001. Prefix with R (remote) or D (SOCKS proxy).',
  'Options avancées': 'Advanced options',
  'Clé privée': 'Private key',
  "Chemin d'une clé OpenSSH (ex. C:\\Users\\vous\\.ssh\\id_ed25519). Les .ppk PuTTY doivent être convertis (PuTTYgen → Export OpenSSH key).":
    'Path to an OpenSSH key (e.g. C:\\Users\\you\\.ssh\\id_ed25519). PuTTY .ppk files must be converted first (PuTTYgen → Export OpenSSH key).',
  'C:\\Users\\vous\\.ssh\\id_ed25519': 'C:\\Users\\you\\.ssh\\id_ed25519',
  'Relais / bastion (ProxyJump)': 'Relay / bastion (ProxyJump)',
  "« user@relais » ou « user@relais:port » — la connexion transite par cette machine. Terminal SSH uniquement pour l'instant.":
    '"user@relay" or "user@relay:port" — the connection is routed through this machine. SSH terminal only for now.',
  'user@bastion.exemple.com': 'user@bastion.example.com',
  'Keep-alive (recommandé — évite les déconnexions des sessions inactives)':
    'Keep-alive (recommended — avoids disconnecting idle sessions)',
  'Transfert X11 (applications graphiques distantes)':
    'X11 forwarding (remote graphical applications)',
  'Compression (liaisons lentes)': 'Compression (slow links)',
  "Le clic ouvre un terminal SSH, l'icône dossier l'explorateur de fichiers (SFTP). Les hôtes de votre":
    'Clicking opens an SSH terminal, the folder icon opens the file browser (SFTP). Hosts from your',
  'apparaissent automatiquement, sans passer par ce formulaire.':
    'appear automatically, without going through this form.',
  Enregistrer: 'Save',
  Ajouter: 'Add',

  // ServerImportDialog.tsx
  'Un serveur de ce nom existe déjà dans GVue': 'A server with this name already exists in GVue',
  'Importer des serveurs': 'Import servers',
  'Recherche des sessions PuTTY/WinSCP…': 'Searching for PuTTY/WinSCP sessions…',
  'Aucune session PuTTY ou WinSCP trouvée sur cette machine (registre et WinSCP.ini vérifiés).':
    'No PuTTY or WinSCP session found on this machine (registry and WinSCP.ini checked).',
  'Fichier ~/.ssh/config': '~/.ssh/config file',
  'Tout décocher': 'Uncheck all',
  'Tout cocher': 'Check all',
  'Importer ({count})': 'Import ({count})',
  'Nom, hôte, utilisateur et port uniquement — les mots de passe ne sont jamais importés : GVue utilise vos clés SSH ou le demande à la connexion.':
    'Name, host, user and port only — passwords are never imported: GVue uses your SSH keys or asks for it at connection time.',

  // ServerItem.tsx
  '{name} — défini dans ~/.ssh/config': '{name} — defined in ~/.ssh/config',
  'Clic : terminal SSH vers {target}': 'Click: SSH terminal to {target}',
  'Clic : terminal SSH': 'Click: SSH terminal',
  'Boutons (au survol) : ▸ terminal · 📂 fichiers (SFTP)':
    'Buttons (on hover): ▸ terminal · 📂 files (SFTP)',
  'Tunnels : {list}': 'Tunnels: {list}',
  'Ouvrir un terminal SSH': 'Open an SSH terminal',
  'Parcourir les fichiers (SFTP)': 'Browse files (SFTP)',
  'Modifier (hôte, tunnels, mot de passe…)': 'Edit (host, tunnels, password…)',
  'Retirer ce serveur': 'Remove this server',
  // ServerManager (refonte 31/07)
  'Serveurs': 'Servers',
  'Rechercher…': 'Search…',
  'Aucun serveur ne correspond.': 'No server matches.',
  'Aucun serveur — créez-en un ou importez.': 'No servers — create one or import.',
  'Nouveau serveur': 'New server',
  'Importer depuis PuTTY, WinSCP ou ~/.ssh/config': 'Import from PuTTY, WinSCP or ~/.ssh/config',
  'Importer': 'Import',
  'Exporter au format ssh_config (compatible VS Code)': 'Export as ssh_config (VS Code compatible)',
  'Exporter': 'Export',
  'Tout retirer (ré-importables ensuite)': 'Remove all (can be re-imported later)',
  '~/.ssh/config — lecture seule': '~/.ssh/config — read-only',
  'Dupliquer en serveur modifiable': 'Duplicate as an editable server',
  'Dupliquer': 'Duplicate',
  'Retirer de la liste': 'Remove from the list',
  'Authentification': 'Authentication',
  'Tunnels': 'Tunnels',
  'Avancé': 'Advanced',
  'Mot de passe': 'Password',
  'Chiffré par Windows (jamais en clair). Vide = demandé à la connexion. Les clés SSH restent plus sûres.':
    'Encrypted by Windows (never stored in plain text). Empty = asked at connection time. SSH keys remain safer.',
  '•••• (laisser vide pour conserver)': '•••• (leave empty to keep)',
  'Format OpenSSH (les .ppk PuTTY doivent être convertis : PuTTYgen → Export OpenSSH key).':
    'OpenSSH format (PuTTY .ppk keys must be converted: PuTTYgen → Export OpenSSH key).',
  'Redirections de port': 'Port forwardings',
  'Cet hôte vient de votre ~/.ssh/config : modifiez le fichier, ou dupliquez-le ici pour une copie modifiable.':
    'This host comes from your ~/.ssh/config: edit the file, or duplicate it here for an editable copy.',
  'Ajouter le serveur': 'Add server',
  '✓ Enregistré': '✓ Saved',
  'Modifications non enregistrées': 'Unsaved changes',
  'Modifications non enregistrées — les abandonner ?': 'Unsaved changes — discard them?',
  'Retirer « {name} » de la liste ?': 'Remove "{name}" from the list?',
  '{n} serveur': '{n} server',
  '{n} serveurs': '{n} servers',
  '« user@hôte » est accepté aussi.': '"user@host" is accepted too.',
  'root, ubuntu, deploy…': 'root, ubuntu, deploy…',
  '⚙ Gérer les serveurs…': '⚙ Manage servers…',
  // Volet SFTP (polish 31/07)
  'Session SFTP active': 'Active SFTP session',
  'connecté': 'connected',
  'Glisser-déposer pour téléverser · téléchargements → dossier local actif':
    'Drag and drop to upload · downloads → active local folder'
}
